spring:
  application:
    name: app-contacts-service
    id: "8872cb73cb054676aeeadfe97f0ba400"
    #id: c7451f279bd847e8a202029f4ffa551e
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    ##测试服
    url: jdbc:mysql://localhost:3306/eprs_contact?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Aa123456

#  redis:
#    host: 10.0.139.141
#    port: 26379
#    jedis:
#      pool:
#        max-active: 20
#        max-idle: 10
#        max-wait: 1000ms
#        min-idle: 5
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  zipkin:
    enabled: true
    base-url: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
      probability: 1
  resources:
    chain:
      cache: false
  mvc:
    static-path-pattern: /**
  cloud:
    refresh:
      refreshable: none
server:
  port: 8094
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
logging:
  level:
    org.bachelor.architecture.eureka: debug

pagehelper:
  reasonable: true
  support-methods-arguments: false
  params: count=countSql
  page-size-zero: true

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      #      defaultZone: http://10.0.139.46:8740/eureka #http://10.30.13.114:8740/eureka #http://localhost:8740/eureka
      defaultZone: http://localhost:8740/eureka #http://10.30.13.114:8740/eureka #http://localhost:8740/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2
    metadata-map:
      api-url: swagger-ui.html
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
bachelor:
  auth:
    up:
      client_filter_enable: false
swagger:
  base-package: "cn.org.bachelor.ms.contacts.controller"
  title: "应急通讯录模块的Restful API"
  version: "1.0"
  description: "由山东易罐云开发"
########################################权限配置########################################
access_token_url: https://yhty.dygzhyq.cn/user-asserver/accessToken
api_url: https://yhty.dygzhyq.cn/user
authorize_url: https://yhty.dygzhyq.cn/user-asserver/appskinoversea/authorize
#应急通讯录客户端
#client_id: c7451f279bd847e8a202029f4ffa551e
#client_secret: 7f537d46c15d44f796e843cc05e475a5
#应急通讯录客户端
client_id: 8872cb73cb054676aeeadfe97f0ba400
client_secret: 01bd345836644d3780cb0d4db17689af
#login.logoutRedirectURL: http://172.17.8.129:8081/index.html
login.logoutRedirectURL: https://wfw.dygzhyq.cn/app-logistics/index.html
logout_url: https://yhty.dygzhyq.cn/user-asserver/logout
mtorg_url: https://yhty.dygzhyq.cn/user/api/mtUserOrgs
#redirect_url: http://172.17.8.129:8081/index.html
#redirect_url: http://w.huagongwuliu.com/dyg
redirect_url: http://10.0.139.239:8089
user_info_url: https://yhty.dygzhyq.cn/user-asserver/userInfo
user_role_url: https://yhty.dygzhyq.cn/user/api/userRoles
org_info_url: https://yhty.dygzhyq.cn/user/api/orgs
user_info_detail: https://yhty.dygzhyq.cn/user/api/userInfoDetail
