spring:
  application:
    name: config-service
  cloud:
    config:
      label: master
      server:
        git:
          uri: D:\work\pdmi\02.projects\tmp\config-repo
          clone-on-start: true
          strict-host-key-checking: false

server:
  port: 8088
eureka:
  client:
    service-url:
#      defaultZone: http://10.30.5.113:8740/eureka/,http://10.30.13.114:8740/eureka/
      defaultZone: http://localhost:8740/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2